// app/lib/complaintCategories.ts

export const studentComplaintCategories = [
  "Faculty",
  "Academic",
  "Examination",
  "Infrastructure",
  "Classroom",
  "Laboratory",
  "Library",
  "Hostel",
  "Food / Canteen",
  "Transport",
  "Administration",
  "Fees / Accounts",
  "Scholarship",
  "Harassment / Misconduct",
  "IT / Technical",
  "Security",
  "Cleanliness",
  "Other",
];

export const facultyComplaintCategories = [
  "Salary / Payroll",
  "Students",
  "Infrastructure",
  "Academic / Department",
  "Colleagues",
  "Administration",
  "Workload",
  "Leave / Attendance",
  "Promotion / Career",
  "Research",
  "Laboratory",
  "IT / Technical",
  "Facilities",
  "Harassment / Misconduct",
  "Security",
  "Other",
];